/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI;

import DAO.Database;
import POJO.NhaCungCap;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class PhieuXuatKho extends javax.swing.JFrame {

    
    /**
     * Creates new form PhieuXuatKho
     */
    public PhieuXuatKho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfTenCuaHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfDiaChi = new javax.swing.JTextField();
        jtfTenHangHoa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfSoLuong = new javax.swing.JTextField();
        jtfDonGia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPhieuXuatHang = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtfNgayGiao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfNhanVien = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfNhanVienGiaoHang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfNgayLap = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PhieuXuatHang");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setText("Phiếu Xuất Hàng");

        jLabel2.setText("Tên cửa hàng");

        jtfTenCuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTenCuaHangActionPerformed(evt);
            }
        });

        jLabel4.setText("Địa chỉ");

        jLabel6.setText("Tên mặt hàng");

        jtfDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDiaChiActionPerformed(evt);
            }
        });

        jLabel7.setText("Đơn giá");

        jLabel9.setText("Số lượng");

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtblPhieuXuatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên cửa hàng", "Địa chỉ", "Ngày giao", "Tên mặt hàng", "Số lượng ", "Đơn giá", "Ngày lập"
            }
        ));
        jScrollPane1.setViewportView(jtblPhieuXuatHang);

        jButton3.setText("Cập nhật");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setText("Ngày giao");

        jLabel3.setText("Nhân viên lập");

        jLabel11.setText("Nhân viên giao hàng");

        jtfNhanVienGiaoHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNhanVienGiaoHangActionPerformed(evt);
            }
        });

        jLabel12.setText("Ngày lập");

        jtfNgayLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNgayLapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfNgayGiao)
                                            .addComponent(jtfTenCuaHang, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                            .addComponent(jtfDonGia)
                                            .addComponent(jtfNgayLap))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(121, 121, 121)
                                                .addComponent(jButton1)
                                                .addGap(42, 42, 42)
                                                .addComponent(jButton2)
                                                .addGap(39, 39, 39)
                                                .addComponent(jButton3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(140, 140, 140)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel11)
                                                            .addComponent(jLabel4))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, 0))
                                                            .addComponent(jtfNhanVienGiaoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jtfNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addComponent(jtfTenHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfTenCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfNgayGiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtfNhanVienGiaoHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jtfNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfTenHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(208, 208, 208))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDiaChiActionPerformed

    private void jtfTenCuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTenCuaHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTenCuaHangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String[] fields = new String[7];
        fields[0] = jtfTenCuaHang.getText();
        fields[1] = jtfDiaChi.getText();
        fields[2] = jtfNgayGiao.getText();
        fields[3] = jtfTenHangHoa.getText();
        fields[4] = jtfSoLuong.getText();
        fields[5] = jtfDonGia.getText();
        fields[6] = jtfNgayLap.getText();
      
//        checkMissingField;
        DefaultTableModel model = (DefaultTableModel) jtblPhieuXuatHang.getModel();
        model.addRow(fields);
        //model.fireTableDataChanged();
        jtblPhieuXuatHang.setModel(model);
        jtblPhieuXuatHang.repaint(); 
        
        Database db = new Database();
        db.connectDB();
        /**
         * code here
         */
        // Find code of NSX from name
        String sql_MCH = "select MaNCC from \"NhaCungCap\" where TenNCC='"+fields[2]+"'";
        ResultSet rs = db.executeQuery(sql_MCH);
        try{
            while (rs.next()){
                String code_NSX = rs.getString("MaNCC");
                System.out.print(code_NSX);
            }
        }catch(Exception e){
        
        }
        // Find code of staff from name
        String sql_MNV = "select MaNV from \"NhanVien\" where TenNV='"+fields[0]+"'";
        rs = db.executeQuery(sql_MNV);
        try{
            while (rs.next()){
                String code_staff = rs.getString("MaNV");
                System.out.print(code_staff);
            }
        }catch(Exception e){
        
        }
        // Find code of product from name
        String MH = "";
     //   String sql_MaMH = "select MaMH from \"MatHang\" where TenMH='"+MH+"'";
        String sql_MaMH = "SELECT \"MaMH\"  FROM \"MatHang\" ";
        
        rs = db.executeQuery(sql_MaMH);
        try{
            while (rs.next()){
                String code_product = rs.getString("MaMH");
                System.out.print(code_product);
            }
        }catch(Exception e){
        
        }
        /*
        String sql = "INSERT INTO \"ChiTietPhieuXuatKho\" (
        "MaPhieuXuat", "MaMatHang", "SoLuong", "DonGia" )VALUES (1, 1, 1, 1)";
        */
        //db.executeUpdate(sql);
        String sql = "INSERT INTO \"ChiTietPhieuXuatKho\" ( MaMatHang, SoLuong, DonGia )VALUES ("+sql_MaMH+",1, 1, 1)";
//        db.executeUpdate(sql);
//        db.disconnectDB();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jtblPhieuXuatHang.getModel();
        
            model.removeRow(jtblPhieuXuatHang.getSelectedRow());
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jtfDiaChi.setText("");
        jtfTenCuaHang.setText("");
        jtfDonGia.setText("");
        jtfNhanVienGiaoHang.setText("");
        jtfNgayLap.setText("");
        jtfSoLuong.setText("");
        jtfNhanVien.setText("");
        jtfNgayGiao.setText("");
        jtfTenHangHoa.setText("");
                
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtfNhanVienGiaoHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNhanVienGiaoHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNhanVienGiaoHangActionPerformed

    private void jtfNgayLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNgayLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNgayLapActionPerformed

    
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
        } catch (InstantiationException ex) {
           
        } catch (IllegalAccessException ex) {
           
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            
        }
        //</editor-fold>

        /* Create and display the form */
        
        PhieuXuatKho pxk = new PhieuXuatKho();
        pxk.setVisible(true);
//      new PhieunhaphangFrame().setVisible(true);

        JLabel lb = new JLabel(" to add new comp ");
        pxk.add(lb);
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblPhieuXuatHang;
    private javax.swing.JTextField jtfDiaChi;
    private javax.swing.JTextField jtfDonGia;
    private javax.swing.JTextField jtfNgayGiao;
    private javax.swing.JTextField jtfNgayLap;
    private javax.swing.JTextField jtfNhanVien;
    private javax.swing.JTextField jtfNhanVienGiaoHang;
    private javax.swing.JTextField jtfSoLuong;
    private javax.swing.JTextField jtfTenCuaHang;
    private javax.swing.JTextField jtfTenHangHoa;
    // End of variables declaration//GEN-END:variables
}
